#:schema node_modules/wrangler/config-schema.json
name = "badge-gen"
main = "src/index.js"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "badge.les.bi"
custom_domain = true
